MiliNeu/Controllers/CollectionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MiliNeu.DataAccess.Data;
using MiliNeu.Models;
using MiliNeu.Models.Services.Interfaces;
using MiliNeu.Models.ViewModels;

namespace MiliNeu.Controllers
{
    public class CollectionsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IConfiguration _configuration;
        private readonly ICollectionService _collectionService;

        public CollectionsController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, IConfiguration configuration, ICollectionService collectionService)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _configuration = configuration;
            _collectionService = collectionService;
        }

        // GET: Collections
        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 5)
        {
            var viewModel = await _collectionService.getCollectionsPageAsync(pageNumber, pageSize);

            string basepath = _configuration["BasePaths:ThumbnailImageBasePath"];
            ViewData["ImageBasePath"] = basepath;
            return View(viewModel);
        }

        //Displays Collections with crud options
        public async Task<IActionResult> Manage()
        {
            return View(await _collectionService.getAllCollectionsAsync());

            /*return _context.Collections != null ?
                        View(await _context.Collections.Include(c => c.Products).ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Collections'  is null.");*/
        }
        // GET: Collections/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Collections == null)
            {
                return NotFound();
            }

            var collection = await _context.Collections
                .FirstOrDefaultAsync(m => m.Id == id);
            if (collection == null)
            {
                return NotFound();
            }

            return View(collection);
        }

        // GET: Collections/Create
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {



            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(CollectionCreateViewModel model, string mainImageName)
        {


            if (ModelState.IsValid)
            {
                // Create a new Collection object
                Collection newCollection = new Collection
                {
                    Name = model.Name,

                    Description = model.Description,
                    Category = model.Category,
                    Price = model.Price,


                };


                string uniqueFileName = null;
                string filePath = _configuration["BasePaths:ThumbnailImageBasePath"];

                //ProductImage Path list for the product
                List<CollectionImage> collectionImages = new List<CollectionImage>();

                if (model.UploadedImages != null && model.UploadedImages.Count > 0)
                {
                    foreach (IFormFile photo in model.UploadedImages)
                    {
                        uniqueFileName = SaveUploadedFile(photo);


                        // Prepare ProductImage Path object for Path List
                        CollectionImage newImage = new CollectionImage
                        {
                            Path = uniqueFileName
                        };
                        if (photo.FileName.Trim() == mainImageName.Trim())
                        {
                            newImage.IsMain = true;
                        }
                        else
                        {
                            newImage.IsMain = false;
                        }
                        //Add ProductImage to List
                        collectionImages.Add(newImage);
                    }

                }

                // Assign the image paths to the product
                newCollection.Images = collectionImages;


                // Add the product to the context (this will generate the ProductId when saved)
                _context.Add(newCollection);

                // Save changes to the database
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));

            }
            return View();

        }

        // GET: Products/Edit/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Collections == null)
            {
                return NotFound();
            }

            var collection = await _context.Collections
                .IgnoreQueryFilters()
                .Include(i => i.Images)
                .SingleAsync(p => p.Id == id);

            if (collection == null)
            {
                return NotFound();
            }

            CollctionEditViewModel model = new CollctionEditViewModel
            {
                Id = collection.Id,
                Name = collection.Name,
                Category = collection.Category,
                Price = collection.Price,
                Description = collection.Description,
                ExistingImages = collection.Images,



            };

            string basepath = _configuration["BasePaths:CollectionImageBasePath"];
            ViewData["ImageBasePath"] = basepath;

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(CollctionEditViewModel model, string mainImageName)
        {


            //Check if model has Id and product table is not null
            if (model.Id < 1 || _context.Collections == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);

                //Get product from database
                Collection collection = _context.Collections
                   .IgnoreQueryFilters()
                   .Include(i => i.Images)
                   .SingleOrDefault(p => p.Id == model.Id);

                if (collection == null)
                {
                    return NotFound();
                }





                if (model.UploadedImages != null && model.UploadedImages.Count > 0)
                {
                    //ProductImage Path list for the product
                    List<CollectionImage> images = new List<CollectionImage>();

                    images = ProcessUploadedFile(model.UploadedImages, mainImageName, collection);

                    //Remove All old images
                    foreach (var image in collection.Images)
                    {
                        _context.CollectionImages.Remove(image);
                    }

                    //Delete images from storage
                    deleteCollectionImages(collection.Images);

                    //Overwrite new images to model
                    collection.Images = images;

                }
                else
                {
                    foreach (var image in collection.Images)
                    {
                        if (image.Path == mainImageName)
                        {
                            image.IsMain = true;
                        }
                        else
                        {
                            image.IsMain = false;
                        }

                    }
                }

                //Map ViewModel properties to product object in database
                collection.Name = model.Name;
                collection.Description = model.Description;
                collection.Category = model.Category;
                collection.Price = model.Price;






                _context.Update(collection);


                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));


            }
            string basepath = _configuration["BasePaths:CollectionImageBasePath"];
            ViewData["ImageBasePath"] = basepath;
            return View();

        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Collections == null)
            {
                return NotFound();
            }

            var collection = await _context.Collections
                .IgnoreQueryFilters()
                .Include(p => p.Images)
                .Include(p => p.Products)
                .ThenInclude(i => i.Variants)
                .ThenInclude(i => i.Images)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (collection == null)
            {
                return NotFound();
            }

            return View(collection);
        }

        // POST: Products/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.Collections == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Collections'  is null.");
            }
            var collection = await _context.Collections
                .IgnoreQueryFilters()
                .Include(i => i.Images)
                .Include(p => p.Products)
                .ThenInclude(p => p.Variants)
                        .ThenInclude(i => i.Images)

MiliNeu/Controllers/ColorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.VisualBasic;
using MiliNeu.DataAccess.Data;
using MiliNeu.Models;
using MiliNeu.Models.ViewModels;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;


namespace Milineu.Controllers
{
    public class ColorsController : Controller
    {
        IConfiguration _configuration;
        ApplicationDbContext _context;
        public ColorsController(IConfiguration configuration, ApplicationDbContext context)
        {
            _configuration = configuration;
            _context = context;
        }
        public async Task<IActionResult> Manage()
        {
            /*Collections collection = new Collections();*/

            return _context.Collections != null ?
                        View(await _context.Colors.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Collections'  is null.");
        }
        // GET: ColorsController
        public ActionResult Index()
        {
            return View(_context.Colors);
        }

        // GET: ColorsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ColorsController/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: ColorsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        // POST: ColorsController/Create
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(ColorViewModel model)
        {
            if (ModelState.IsValid)
            {
                Color color = new Color
                {
                    Name = model.ColorName,
                    HexCode = model.HexCode
                };

                _context.Colors.Add(color);
                await _context.SaveChangesAsync(); // Awaiting the async method

                return RedirectToAction(nameof(Index));
            }

            // Return the view again with the invalid model for the user to fix
            return View(model);
        }


        // GET: ColorsController/Edit/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            // Find the color in the database by its ID
            Color color = await _context.Colors.SingleOrDefaultAsync(c => c.Id == id);

            if (color == null)
            {
                return NotFound(); // Return a 404 if the color doesn't exist
            }

            // Populate the ColorViewModel with the data from the color entity
            ColorViewModel model = new ColorViewModel
            {
                ColorID = id,
                ColorName = color.Name,
                HexCode = color.HexCode
            };

            return View(model); // Return the populated model to the view
        }


        // POST: ColorsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(ColorViewModel model)
        {
            // Validate ColorID
            if (model.ColorID <= 0) // Assuming ID is positive
            {
                return BadRequest("Invalid Color ID.");
            }

            // Check if the model state is valid
            if (ModelState.IsValid)
            {
                // Retrieve the existing color from the database
                var color = await _context.Colors.FindAsync(model.ColorID);

                if (color == null)
                {
                    return NotFound();
                }

                // Update the properties
                color.Name = model.ColorName;
                color.HexCode = model.HexCode;

                // Save changes to the database
                _context.Update(color);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            // Return the view with the current model if validation fails
            return View(model);
        }


        // GET: ColorsController/Delete/5
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            // Find the color in the database by its ID
            Color color = await _context.Colors.SingleOrDefaultAsync(c => c.Id == id);

            if (color == null)
            {
                return NotFound(); // Return a 404 if the color doesn't exist
            }

            // Populate the ColorViewModel with the data from the color entity
            ColorViewModel model = new ColorViewModel
            {
                ColorName = color.Name,
                HexCode = color.HexCode
            };
            return View(model);

        }

        // POST: ColorsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            if (ModelState.IsValid)
            {
                Color color = _context.Colors.Single(c => c.Id == id);
                if (color == null)
                {
                    return NotFound();
                }
                _context.Remove(color);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }

            return View();
        }
    }
}

MiliNeu/Controllers/UpdatesController.cs
using Microsoft.AspNetCore.Mvc;
using MiliNeu.DataAccess.Data;
using MiliNeu.Models;
using MiliNeu.Utility;

namespace MiliNeu.Controllers
{
    public class UpdatesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ISendGridService _sendGridService;
        public UpdatesController(ApplicationDbContext dbContext, ISendGridService sendGridService)
        {
            _context = dbContext;
            _sendGridService = sendGridService;
        }
        public IActionResult Index()
        {
            return View();
        }
        // GET: Admin page to create email
        public IActionResult CreateEmail()
        {
            return View();
        }

        // POST: Send manually created email
        [HttpPost]
        public async Task<IActionResult> SendManualEmail(string subject, string body)
        {
            if (string.IsNullOrEmpty(subject) || string.IsNullOrEmpty(body))
            {
                ModelState.AddModelError("", "Subject and Body are required.");
                return View("CreateEmail");
            }
            try
            {
                // Retrieve the list of subscribed emails
                IEnumerable<Subscriber>? subscribers = _context.Subscribers?.Where(c => c.IsActive == true);
                if (subscribers != null && subscribers.Count() > 0)
                {
                    foreach (var subscriber in subscribers)
                    {
                        // Send the email
                        await _sendGridService.SendEmailAsync("Milineu Subscriber", subscriber.Email, subject, body);
                    }
                    // Return a success message
                    ViewData["Message"] = "Email sent successfully!";
                }
                else
                {
                    // Return a success message
                    ViewData["Message"] = "There are no Subscribers";
                }





            }
            catch (Exception)
            {

                ViewData["Message"] = "Error Occured while Sending Emails.";

            }
            return View("CreateEmail");


        }
    }
}

MiliNeu/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    string imageBasePath = ViewData["ImageBasePath"].ToString();
}

<div class="page-title">
    <h1 class="fade-out-left">ABOUT BRAND</h1>

</div>
<div class="about-content">
    <p class="fade-out-left">
        Milineu is built on the principles of community, culture, and comfort. We believe in offering affordable luxury that transcends fleeting trends, focusing instead on timeless pieces that are true wardrobe investments. Our mission is simple: to create clothing that’s both innovative and effortlessly wearable, while championing local talent and craftsmanship at every step.
    <p>
    <p class="fade-out-left">
        A strong sense of community shapes the brand’s approach to design. With comfort at the heart of every piece, the brand strives to become a go-to favorite in your wardrobe with its effortlessly wearable styles. By reimagining traditional silhouettes and forms, the label strikes a perfect balance—timeless and classic, yet undeniably modern.
    </p>
</div>

@await Html.PartialAsync("_SubscribeSection")
@await Html.PartialAsync("_Socials")
@await Html.PartialAsync("_Footer")

MiliNeu/Views/Home/Index.cshtml
@model MiliNeu.Models.ViewModels.HomeViewModel

@{
    ViewData["Title"] = "Home";
    string imageBasePath = ViewData["ImageBasePath"].ToString();
}









<section class="carousel">

    <div class="carousel-images">
        @if (Model.HeroSections==null|| !Model.HeroSections.Any(c=>c.IsActive))
        {
            @foreach (var collection in Model.AllCollections)
            {
                <div class="item-carousel">
                    <img loading="lazy" src="/Resources/Images/Collections/@(collection.Images.FirstOrDefault(i=>i.IsMain).Path)" alt="Image 1">
                    <div class="cta">
                        <p class="fade-out-bottom">BESTSELLERS</p>
                        <a class="fade-out-bottom" href="/Products/BestSellers">SHOP NOW</a>
                    </div>
                    
                </div>



            }
        }
        else
        {
            
            @foreach (var heroSection in Model.HeroSections)
            {
                if (heroSection.IsActive==true)
                {
                    <div class="item-carousel">
                        <img loading="lazy" src="/Resources/Images/HeroSection/@(heroSection.Image.Path)" alt="@(heroSection.Image.Path)">
                        <div class="cta">
                            <p class="fade-out-bottom">@heroSection.Title</p>
                            <a class="fade-out-bottom" href="@heroSection.Link">SHOP NOW</a>
                        </div>
                    </div>
                }
                



            }
            @* <div class="item-carousel">
                <video src="/Resources/video/BellaHadid2.mp4" autoplay muted loop></video>
                <div class="cta">
                    <p>BestSellers</p>
                    <a href="/Products/BestSellers">SHOP NOW</a>
                </div>
            </div> *@
        }
        


    </div>

    <!-- Carousel navigation -->
    <a class="prev" onclick="changeSlide(-1)"> 
        <svg role="img" xmlns="http://www.w3.org/2000/svg" width="40px" height="40px" viewBox="0 0 24 24" aria-labelledby="chevronLeftIconTitle" stroke="#000000" stroke-width="0.75" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000"> <title id="chevronLeftIconTitle">Chevron Left</title> <polyline points="14 18 8 12 14 6 14 6" /> </svg>
    </a>
    <a class="next" onclick="changeSlide(1)"> 
        <svg role="img" xmlns="http://www.w3.org/2000/svg" width="40px" height="40px" viewBox="0 0 24 24" aria-labelledby="chevronRightIconTitle" stroke="#000000" stroke-width="0.75" stroke-linecap="round" stroke-linejoin="round" fill="none" color="#000000"> <title id="chevronRightIconTitle">Chevron Right</title> <polyline points="10 6 16 12 10 18 10 18" /> </svg>
    </a>
</section>



<section>
    <p class="section-heading fade-out-left">BESTSELLERS</p>
    @await Html.PartialAsync("_gallery", Model.BestSellers)

    <div class="cta-product-all fade-out-bottom">
        <a href="/Products">VIEW ALL</a>
    </div>
</section>




@await Html.PartialAsync("_CategorySelection")


@await Html.PartialAsync("_SubscribeSection")


@await Html.PartialAsync("_Socials")


@await Html.PartialAsync("_Footer")



@section scripts {
    <script async src="~/js/Carousel.js"></script>
}

MiliNeu/Views/Home/Manage.cshtml
<title>Manage</title>
<style>
    /* Optional: Add some basic styling for better presentation */


    .link-container {
        display: grid;
        grid-template-columns:1fr 1fr 1fr 1fr 1fr;
        grid-template-rows:1fr;

        justify-items: start;
        background-color: #f2f2f2;
        padding: 15px;
        border-radius: 0px;
        font-size: 1rem;
    }

        .link-container a {
            text-decoration: none;
            color: #333;
            padding: 8px 12px;
            border: 1px solid #ddd;
            border-radius: 3px;
            transition: background-color 0.3s;
        }

            .link-container a:hover {
                background-color: #ddd;
            }


         
</style>


@if (User.IsInRole("Admin"))
{
    <div class="link-container">
        <div>
            <a asp-action="Manage" asp-controller="Orders">Manage Orders</a>
        </div>
        <div>
        <a asp-action="Manage" asp-controller="Collections">Manage Collections</a>
        </div>

    <div>
        <a asp-action="Manage" asp-controller="Products">Manage Products</a>
    </div>
        <div>
            <a asp-action="Manage" asp-controller="Colors">Manage Colors</a>
        </div>
        <div>
            <a asp-action="Index" asp-controller="HeroSections">Manage Hero Section</a>
        </div>
        
        
       
    </div>
    <div class="link-container">
        
        <div>
            <a asp-action="AuditLog" asp-controller="Orders">Audit Log</a>
        </div>
        <div>
            <a asp-action="CreateEmail" asp-controller="Updates">Email Subscribers</a>
        </div>



    </div>
}

MiliNeu/Views/Home/_CategorySelection.cshtml
<section>
    <div class="category-container fade-out-bottom">
    <div class="category">
        <a asp-controller="Products" asp-action="ProductsByCategory" asp-route-categoryId="1">
            <img loading="lazy" src="/Resources/Images/Banner/sydney-sweeney1.jpg" />
            <label>WOMEN</label>
        </a>

    </div>
    <div class="category">
        <a asp-controller="Products" asp-action="ProductsByCategory" asp-route-categoryId="2">
            <img loading="lazy" src="/Resources/Images/Banner/ana-de-armas1.jpg" />
            <label>UNISEX</label>
        </a>
    </div>
</div>

</section>