MiliNeu/Controllers/AddressesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MiliNeu.DataAccess.Data;
using MiliNeu.Models;
using MiliNeu.Models.ViewModels;
using System.Security.Claims;

namespace MiliNeu.Controllers
{
    public class AddressesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AddressesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Addresses
        public async Task<IActionResult> Index()
        {

            var addresses = _context.Address.Include(a => a.User);

            AddressVM addressVM = new AddressVM()
            {
                Addresses = addresses,
            };

            return View(addresses);
        }
        // GET: Addresses
        public async Task<IActionResult> GetAddresses()
        {
            string? userId = HttpContext.User?.FindFirstValue(ClaimTypes.NameIdentifier);
            var addresses = _context.Address.Include(a => a.UserId == userId);

            AddressVM addressVM = new AddressVM()
            {
                Addresses = addresses,
            };

            return PartialView("_SavedAddresses", addressVM);
        }

        // GET: Addresses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Address
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // GET: Addresses/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Addresses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,Name,StreetAddress,ApartmentSuite,City,State,PostalCode,Country,PhoneNumber,Email,IsPrimary")] Address address)
        {
            if (ModelState.IsValid)
            {
                _context.Add(address);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", address.UserId);
            return View(address);
        }

        // GET: Addresses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Address.FindAsync(id);
            if (address == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", address.UserId);
            return View(address);
        }

        // POST: Addresses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,Name,StreetAddress,ApartmentSuite,City,State,PostalCode,Country,PhoneNumber,Email,IsPrimary")] Address address)
        {
            if (id != address.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(address);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AddressExists(address.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", address.UserId);
            return View(address);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateOrderAddress(ShippingAddress orderAddress)
        {
            string? userId = HttpContext.User?.FindFirstValue(ClaimTypes.NameIdentifier);


            /*if (id != address.Id)
            {
                return NotFound();
            }
*/
            if (ModelState.IsValid)
            {
                try
                {


                    _context.Update(orderAddress);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
            }
            /*ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", address.UserId);*/
            return RedirectToAction("Index", "Home");
        }

        // GET: Addresses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var address = await _context.Address
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (address == null)
            {
                return NotFound();
            }

            return View(address);
        }

        // POST: Addresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var address = await _context.Address.FindAsync(id);
            if (address != null)
            {
                _context.Address.Remove(address);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AddressExists(int id)
        {
            return _context.Address.Any(e => e.Id == id);
        }
    }
}

MiliNeu/Controllers/OrderIssuesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MiliNeu.DataAccess.Data;
using MiliNeu.Models;
using System.Security.Claims;

namespace MiliNeu.Controllers
{
    public class OrderIssuesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderIssuesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: OrderIssues
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.OrderIssues.Include(o => o.Order).Include(o => o.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: OrderIssues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderIssue = await _context.OrderIssues
                .Include(o => o.Order)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderIssue == null)
            {
                return NotFound();
            }

            return View(orderIssue);
        }
        [HttpPost]
        public async Task<IActionResult> ReportIssue([FromBody] OrderIssue model)
        {
            var orderIssue = new OrderIssue
            {
                OrderId = model.OrderId,
                UserId = User.FindFirstValue(ClaimTypes.NameIdentifier), // Get the logged-in user
                IssueType = model.IssueType,
                Description = model.Description,
                CreatedDate = DateTime.UtcNow,
                Status = "Pending",
                AdditionalData = model.Description

            };

            _context.OrderIssues.Add(orderIssue);
            await _context.SaveChangesAsync();

            return Ok(new { message = "Issue reported successfully!" });

        }

        // GET: OrderIssues/Create
        public IActionResult Create()
        {
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "Currency");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: OrderIssues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,OrderId,IssueType,Description,CreatedDate,Status,ResolvedDate,UserId,AdditionalData")] OrderIssue orderIssue)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderIssue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "Currency", orderIssue.OrderId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", orderIssue.UserId);
            return View(orderIssue);
        }

        // GET: OrderIssues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderIssue = await _context.OrderIssues.FindAsync(id);
            if (orderIssue == null)
            {
                return NotFound();
            }
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "Currency", orderIssue.OrderId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", orderIssue.UserId);
            return View(orderIssue);
        }

        // POST: OrderIssues/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,OrderId,IssueType,Description,CreatedDate,Status,ResolvedDate,UserId,AdditionalData")] OrderIssue orderIssue)
        {
            if (id != orderIssue.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderIssue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderIssueExists(orderIssue.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrderId"] = new SelectList(_context.Orders, "Id", "Currency", orderIssue.OrderId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", orderIssue.UserId);
            return View(orderIssue);
        }

        // GET: OrderIssues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderIssue = await _context.OrderIssues
                .Include(o => o.Order)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (orderIssue == null)
            {
                return NotFound();
            }

            return View(orderIssue);
        }

        // POST: OrderIssues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orderIssue = await _context.OrderIssues.FindAsync(id);
            if (orderIssue != null)
            {
                _context.OrderIssues.Remove(orderIssue);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderIssueExists(int id)
        {
            return _context.OrderIssues.Any(e => e.Id == id);
        }
    }
}

MiliNeu/Views/Orders/AuditLog.cshtml
@model IEnumerable<MiliNeu.Models.PaymentStatusAudit>
@{

}
<p class="page-title">Audits Log</p>
<table class="table">
    <thead>
        <tr>
            <th>Old Status</th>
            <th>New Status</th>
            <th>Date Changed</th>
            <th>Changed By</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var log in Model)
        {
            <tr>
                <td>@log.OldStatus</td>
                <td>@log.NewStatus</td>
                <td>@log.DateChanged.ToString("g")</td>
                <td>@log.ChangedBy</td>
            </tr>
        }
    </tbody>
</table>

MiliNeu/Views/Orders/Checkout.cshtml
@model MiliNeu.Models.ViewModels.CheckoutVM
@{
    Layout = "_LayoutCheckout";
    ViewData["Title"] = "Checkout";
    string imageBasePath = ViewData["ImageBasePath"].ToString();
}



<div class="checkout">
   


    <div class="checkout-left">
        
        <form id="checkout-form" method="post" asp-controller="Orders" asp-action="PostCheckout">
          <input type="text" hidden asp-for="EstimatedDelivery" value="@Model.EstimatedDelivery" />
            <h4>Account</h4>
            <div class="form-group">
                
                <input asp-for="@Model.Email" readonly class="form-control" />
                <span asp-validation-for="@Model.Email" class="text-danger"></span>
            </div>
            <section class="estimated-delivery">
                <h4>Estimated delivery</h4>
                <p>@Model.EstimatedDelivery</p>
            </section>
            <h4>Shipping address</h4>
            @if (Model.AddressVM.Addresses==null||Model.AddressVM.Addresses.Count()<1)
            {
                <p>No saved addresses found.</p>

                @await Html.PartialAsync("_AddressForm", Model.AddressVM)
            }
            else
            {
                @await Html.PartialAsync("_SavedAddresses", Model.AddressVM)
            }
            
            
            <div class="form-group">

                <textarea asp-for="@Model.CustomerNotes" placeholder="Notes" class="form-control" rows="3"></textarea>
                <span asp-validation-for="@Model.CustomerNotes" class="text-danger"></span>
            </div>
            <div class="order-container">
                <p><strong>Order Summary</strong></p>

                @foreach (var item in Model.CartItems)
                {
                    <div class="order-item">
                        <div class="item-thumbnail">
                            <img src="@($"{imageBasePath}{item.ProductVariant.Images.FirstOrDefault(i=>i.IsMain).Path}")" />
                            <div class="quantity">
                                <p>@item.Quantity</p>
                            </div>

                        </div>
                        <div class="item-details">
                            <p>@item.Product.Name</p>
                            <p>@($"{item.SelectedSize} / {item.ProductVariant.Color.Name}")</p>
                        </div>
                        <div class="item-price">
                            @if (item.Product.DiscountedPrice > 0)
                            {

                                <p><span>@($"{"INR " + item.Product.Price} ")</span> <span>@($"{"INR " + item.Product.DiscountedPrice}")</span></p>
                            }
                            else
                            {
                                <p>@($"{"INR " + item.Product.Price}")</p>
                            }

                        </div>
                    </div>
                }

                <div class="order-summary">
                    <p><span> Subtotal</span><span>@("INR " + Model.Subtotal) </span> </p>
                    <p><span>Shipping</span><span>@("INR " + Model.Shipping) </span> </p>
                    <p><span>Total</span><span>@("INR " + Model.Total) </span> </p>

                </div>
            </div>
            
            <div class="text-center mb-5">
                <button type="submit" class="btn-checkout">Pay Now</button>
            </div>
        </form>
    </div>
    <div class="checkout-right">

        <div class="order-container">
            <p><strong>Order Summary</strong></p>

            @foreach (var item in Model.CartItems)
            {
                <div class="order-item">    
                    <div class="item-thumbnail">
                        <img src="@($"{imageBasePath}{item.ProductVariant.Images.FirstOrDefault(i=>i.IsMain).Path}")" />
                        <div class="quantity">
                            <p>@item.Quantity</p>
                        </div>
                       
                    </div>
                    <div class="item-details">
                        <p>@item.Product.Name</p>
                        <p>@($"{item.SelectedSize} / {item.ProductVariant.Color.Name}")</p>
                    </div>
                    <div class="item-price">
                        @if (item.Product.DiscountedPrice>0)
                        {

                            <p><span>@($"{"INR " + item.Product.Price} ")</span> <span>@($"{"INR " + item.Product.DiscountedPrice}")</span></p>
                        }
                        else
                        {
                            <p>@($"{"INR " + item.Product.Price}")</p>
                        }

                    </div>  
                </div>
            }

            
            <div class="order-summary">
                <p><span> Subtotal</span><span>@("INR " + Model.Subtotal) </span> </p>
                <p><span>Discount</span><span>@("- INR " + Model.Discount) </span> </p>
                <p><span>Shipping</span><span>@("INR " + Model.Shipping) </span> </p>
                <p><span>Total</span><span>@("INR " + Model.Total) </span> </p>

            </div>
        </div>
        
    </div>

</div>


@section Scripts {

}

MiliNeu/Views/Orders/Failure.cshtml
@{
    ViewData["Title"] = "Payment Failed";
}

<h1>Payment Failed</h1>
<p>There was an issue with your payment. Please try again or contact support if the issue persists.</p>

MiliNeu/Views/Orders/_HelpModal.cshtml
@model int






<div class="help-modal">
    <div class="wrapper">
        <form id="help-modal-issue" action="">
            <label for="ItemNotDelivered">Item Not Delivered</label>
            <input name="issue" required hidden id="ItemNotDelivered" value="Item Not Delivered" type="radio">

            <label for="ItemDamaged">Item Damaged</label>
            <input name="issue" hidden id="ItemDamaged" value="Item Damaged" type="radio">

            <label for="WrongItemReceived">Wrong Item Received</label>
            <input name="issue" hidden id="WrongItemReceived" value="Wrong Item Received" type="radio">

            <label for="Other">Other</label>
            <input name="issue" hidden id="Other" value="Other" type="radio">
            <div class="btn-box">
                
                <button class="cancel" type="button">Cancel</button>

            </div>
        </form>
        <form id="help-modal-description" action="">
            <input type="text" readonly required hidden name="order-id" value="@Model" />
            <h3>Please describe the issue</h3>
            <p id="selected-issue-display" style="font-weight: bold;"></p> <!-- Placeholder for selected issue -->

            <textarea name="description" required id="comments" rows="4" cols="50"></textarea>


            <div class="btn-box">
                <button id="Back2" type="button">Back</button>
                <button class="cancel" type="button">Cancel</button>
                <button id="help-modal-Submit" type="button">Submit</button>

            </div>
        </form>
        <div class="step-row">
            <div id="progress"></div>
            <div class="step-col">
                <small>Select Issue</small>
            </div>
            <div class="step-col">
                <small>Describe the Issue</small>
            </div>

        </div>
    </div>
</div>



<script>
    document.getElementById("helpLink").addEventListener('click',()=>{
        helpModal.style.display = "flex";
    })
    var stepCol = document.getElementsByClassName('step-col')[1];
    var submitButton = document.getElementById('help-modal-Submit');
    var helpModal = document.getElementsByClassName("help-modal")[0];
    var issueForm = document.getElementById("help-modal-issue");
    var descriptionForm = document.getElementById("help-modal-description");

    const issue = document.querySelectorAll('input[name="issue"]');
    var Back2 = document.getElementById("Back2");
    var CancelBtns = document.getElementsByClassName("cancel");

    var Progress = document.getElementById("progress");

    issue.forEach(element => {
        element.addEventListener('click', () => {
            issueForm.style.opacity = "0";
            descriptionForm.style.left = "0";
            descriptionForm.style.opacity = "1";
            Progress.style.width = "100%";
            stepCol.style.color = "#fff";

        })
    })


    Array.from(CancelBtns).forEach(element => {
        element.addEventListener('click', () => {
            helpModal.style.display = "none";
            issueForm.style.opacity = "1";
            descriptionForm.style.left = "450px";
            descriptionForm.style.opacity = "0";
            Progress.style.width = "50%";
            stepCol.style.color = "#000";

        });
    }); 

    Back2.addEventListener('click', () => {
        issueForm.style.opacity = "1";
        descriptionForm.style.left = "450px";
        descriptionForm.style.opacity = "0";
        Progress.style.width = "50%";
        stepCol.style.color = "#000";

    });
    const selectedIssueDisplay = document.getElementById("selected-issue-display");


    // Listen for radio button selection in the first form
    issueForm.addEventListener("change", (event) => {
        if (event.target.name === "issue") {
            const selectedIssue = event.target.value; // Get the selected issue value
            // Update the second form with the selected issue
            selectedIssueDisplay.textContent = `Issue: ${selectedIssue}`;
        }
    });

    submitButton.addEventListener('click',()=>{
        // Collect data from the first form
        const issueData = new FormData(issueForm);
        const selectedIssue = issueData.get("issue"); // Gets the selected radio value

        // Collect data from the second form
        const descriptionData = new FormData(descriptionForm);
        const issueDescription = descriptionData.get("description"); // Gets the textarea value
        const orderId = descriptionData.get("order-id"); // Gets the textarea value

        // Validation: Check if all required fields are filled
        let validationErrors = [];

        if (!selectedIssue) {
            validationErrors.push("Please select an issue type.");
        }

        if (!issueDescription || issueDescription.trim() === "") {
            validationErrors.push("Please describe the issue.");
        }

        if (!orderId || orderId.trim() === "") {
            validationErrors.push("Order ID is required.");
        }

        // If there are validation errors, display them and stop submission
        if (validationErrors.length > 0) {
            alert(validationErrors.join("\n"));
            return;
        }
        // Combine both data into one object
        const combinedData = {
            IssueType: selectedIssue,
            Description: issueDescription,
            OrderId: orderId,
        };

        // POST the combined data to the server
        fetch('/OrderIssues/ReportIssue', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(combinedData),
        })
            .then(response => {
                if (response.ok) {
                    alert("Your issue has been submitted successfully!");
                    document.querySelector(".help-modal").style.display = "none";
                } else {
                    alert("There was an error submitting your issue.");
                }
            })
            .catch(error => {
                console.error("Error:", error);
            });
    });
</script>




































@* 
<!-- Modal Structure -->
<div id="helpModal" class="modal">
    <div class="modal-content">
        <span class="close-button">&times;</span>

        <!-- Step 1: Reason Selection -->
        <div id="step1" class="modal-step">
            <h2>What's the issue with your order?</h2>
            <ul class="options">
                <li><button class="reason-btn" data-reason="Return Item">Return Item</button></li>
                <li><button class="reason-btn" data-reason="Order Not Delivered">Order Not Delivered</button></li>
                <li><button class="reason-btn" data-reason="Damaged Item">Damaged Item</button></li>
                <li><button class="reason-btn" data-reason="Something Else">Something Else</button></li>
            </ul>
        </div>

        <!-- Step 2: More Information -->
        <div id="step2" class="modal-step" style="display: none;">
            <h2>Provide More Information</h2>
            <p id="selectedReasonText"></p>
            <form id="helpForm" asp-controller="OrderIssues" asp-action="ReportIssue">
                
                <label for="issue">Describe your issue:</label>
                <textarea id="issue" name="issue" placeholder="Provide more details..." required></textarea>

                <button type="button" id="backButton">Back</button>
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>
 *@
@* 
<script>
    document.addEventListener("DOMContentLoaded", () => {
        const helpLink = document.getElementById("helpLink");
        const modal = document.getElementById("helpModal");
        const closeButton = document.querySelector(".close-button");
        const step1 = document.getElementById("step1");
        const step2 = document.getElementById("step2");
        const reasonButtons = document.querySelectorAll(".reason-btn");
        const selectedReasonText = document.getElementById("selectedReasonText");
        const backButton = document.getElementById("backButton");
        const helpForm = document.getElementById("helpForm");

        let selectedReason = ""; // Variable to store selected reason

        // Show the modal
        helpLink.addEventListener("click", (e) => {
            e.preventDefault();
            modal.style.display = "block";
            step1.style.display = "block";
            step2.style.display = "none";
        });

        // Close the modal
        closeButton.addEventListener("click", () => {
            modal.style.display = "none";
        });

        // Close the modal when clicking outside the modal content
        window.addEventListener("click", (e) => {
            if (e.target === modal) {
                modal.style.display = "none";
            }
        });

        // Handle reason selection
        reasonButtons.forEach((button) => {
            button.addEventListener("click", () => {
                selectedReason = button.getAttribute("data-reason");
                selectedReasonText.textContent = `You selected: ${selectedReason}`;
                step1.style.display = "none";
                step2.style.display = "block";
            });
        });

        // Go back to Step 1
        backButton.addEventListener("click", () => {
            step1.style.display = "block";
            step2.style.display = "none";
        });

        // Handle form submission
        helpForm.addEventListener("submit", (e) => {
            e.preventDefault();
            const orderId = document.getElementById("orderId").value;
            const issue = document.getElementById("issue").value;

            console.log(`Selected Reason: ${selectedReason}`);
            console.log(`Order ID: ${orderId}`);
            console.log(`Issue: ${issue}`);

            alert("Your issue has been submitted. We'll get back to you shortly.");
            modal.style.display = "none";
        });
    });

</script> *@

MiliNeu/Views/Orders/_SavedAddresses.cshtml
@model MiliNeu.Models.ViewModels.AddressVM
<!-- "Delivering to" Section -->
<div class="delivery-info">

    <div id="delivery-address">
        @foreach (var address in Model.Addresses)
        {
            if (address.IsPrimary)
            {
                <p>@address.FirstName<span> </span>@address.LastName</p>
                <p><span>@address.ApartmentSuite ,@address.StreetAddress, @address.City, @address.Country, @address.PostalCode</span></p>
                <p><span>Phone Number:</span>@address.PhoneNumber</p>
                <a asp-controller="Addresses" asp-action="Edit" asp-route-id="@address.Id">Edit</a>
            }



        }
    </div>
    <!-- Collapsible List of Addresses -->
    <span asp-validation-for="@Model.SelectedAddressId" class="text-danger"></span>

    <button class="collapsible">Change</button>
    <div class="content">
        @foreach (var address in Model.Addresses)
        {

            <label class="item">
                @if (address.IsPrimary)
                {
                    <input type="radio" checked required name="AddressVM.SelectedAddressId" asp-for="SelectedAddressId" value="@address.Id" class="address-radio">

                }
                else
                {
                    <input type="radio" required name="AddressVM.SelectedAddressId" asp-for="SelectedAddressId" value="@address.Id" class="address-radio">

                }

                <div class="item-details">
                    <p>@address.FirstName <span> </span>@address.LastName</p>
                    <p><span>@address.ApartmentSuite ,@address.StreetAddress, @address.City, @address.Country, @address.PostalCode</span></p>
                    <p><span>Phone Number:</span>@address.PhoneNumber</p>
                    <a asp-controller="Addresses" asp-action="Edit" asp-route-id="@address.Id">Edit</a> |

                </div>
            </label>
        }




    </div>

</div>